// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package tutorial

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message int32

const (
	Message_Unknow Message = 0
	// request
	Message_Message_XX1Request Message = 1
	Message_Message_XX2Request Message = 2
	// response
	Message_Message_XX1Response Message = 1048577
	Message_Message_XX2Response Message = 1048578
)

var Message_name = map[int32]string{
	0:       "Unknow",
	1:       "Message_XX1Request",
	2:       "Message_XX2Request",
	1048577: "Message_XX1Response",
	1048578: "Message_XX2Response",
}

var Message_value = map[string]int32{
	"Unknow":              0,
	"Message_XX1Request":  1,
	"Message_XX2Request":  2,
	"Message_XX1Response": 1048577,
	"Message_XX2Response": 1048578,
}

func (x Message) String() string {
	return proto.EnumName(Message_name, int32(x))
}

func (Message) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

type XX1Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XX1Request) Reset()         { *m = XX1Request{} }
func (m *XX1Request) String() string { return proto.CompactTextString(m) }
func (*XX1Request) ProtoMessage()    {}
func (*XX1Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *XX1Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XX1Request.Unmarshal(m, b)
}
func (m *XX1Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XX1Request.Marshal(b, m, deterministic)
}
func (m *XX1Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XX1Request.Merge(m, src)
}
func (m *XX1Request) XXX_Size() int {
	return xxx_messageInfo_XX1Request.Size(m)
}
func (m *XX1Request) XXX_DiscardUnknown() {
	xxx_messageInfo_XX1Request.DiscardUnknown(m)
}

var xxx_messageInfo_XX1Request proto.InternalMessageInfo

func (m *XX1Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type XX2Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XX2Request) Reset()         { *m = XX2Request{} }
func (m *XX2Request) String() string { return proto.CompactTextString(m) }
func (*XX2Request) ProtoMessage()    {}
func (*XX2Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *XX2Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XX2Request.Unmarshal(m, b)
}
func (m *XX2Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XX2Request.Marshal(b, m, deterministic)
}
func (m *XX2Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XX2Request.Merge(m, src)
}
func (m *XX2Request) XXX_Size() int {
	return xxx_messageInfo_XX2Request.Size(m)
}
func (m *XX2Request) XXX_DiscardUnknown() {
	xxx_messageInfo_XX2Request.DiscardUnknown(m)
}

var xxx_messageInfo_XX2Request proto.InternalMessageInfo

func (m *XX2Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type XX1Response struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XX1Response) Reset()         { *m = XX1Response{} }
func (m *XX1Response) String() string { return proto.CompactTextString(m) }
func (*XX1Response) ProtoMessage()    {}
func (*XX1Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *XX1Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XX1Response.Unmarshal(m, b)
}
func (m *XX1Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XX1Response.Marshal(b, m, deterministic)
}
func (m *XX1Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XX1Response.Merge(m, src)
}
func (m *XX1Response) XXX_Size() int {
	return xxx_messageInfo_XX1Response.Size(m)
}
func (m *XX1Response) XXX_DiscardUnknown() {
	xxx_messageInfo_XX1Response.DiscardUnknown(m)
}

var xxx_messageInfo_XX1Response proto.InternalMessageInfo

func (m *XX1Response) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type XX2Response struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XX2Response) Reset()         { *m = XX2Response{} }
func (m *XX2Response) String() string { return proto.CompactTextString(m) }
func (*XX2Response) ProtoMessage()    {}
func (*XX2Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *XX2Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XX2Response.Unmarshal(m, b)
}
func (m *XX2Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XX2Response.Marshal(b, m, deterministic)
}
func (m *XX2Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XX2Response.Merge(m, src)
}
func (m *XX2Response) XXX_Size() int {
	return xxx_messageInfo_XX2Response.Size(m)
}
func (m *XX2Response) XXX_DiscardUnknown() {
	xxx_messageInfo_XX2Response.DiscardUnknown(m)
}

var xxx_messageInfo_XX2Response proto.InternalMessageInfo

func (m *XX2Response) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MessageHeader struct {
	MessageType          Message  `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=tutorial.Message" json:"message_type,omitempty"`
	MessageLength        int32    `protobuf:"varint,2,opt,name=message_length,json=messageLength,proto3" json:"message_length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageHeader) Reset()         { *m = MessageHeader{} }
func (m *MessageHeader) String() string { return proto.CompactTextString(m) }
func (*MessageHeader) ProtoMessage()    {}
func (*MessageHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *MessageHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageHeader.Unmarshal(m, b)
}
func (m *MessageHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageHeader.Marshal(b, m, deterministic)
}
func (m *MessageHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageHeader.Merge(m, src)
}
func (m *MessageHeader) XXX_Size() int {
	return xxx_messageInfo_MessageHeader.Size(m)
}
func (m *MessageHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageHeader.DiscardUnknown(m)
}

var xxx_messageInfo_MessageHeader proto.InternalMessageInfo

func (m *MessageHeader) GetMessageType() Message {
	if m != nil {
		return m.MessageType
	}
	return Message_Unknow
}

func (m *MessageHeader) GetMessageLength() int32 {
	if m != nil {
		return m.MessageLength
	}
	return 0
}

func init() {
	proto.RegisterEnum("tutorial.Message", Message_name, Message_value)
	proto.RegisterType((*XX1Request)(nil), "tutorial.XX1Request")
	proto.RegisterType((*XX2Request)(nil), "tutorial.XX2Request")
	proto.RegisterType((*XX1Response)(nil), "tutorial.XX1Response")
	proto.RegisterType((*XX2Response)(nil), "tutorial.XX2Response")
	proto.RegisterType((*MessageHeader)(nil), "tutorial.MessageHeader")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x28, 0x29, 0x2d, 0xc9, 0x2f,
	0xca, 0x4c, 0xcc, 0x51, 0x52, 0xe0, 0xe2, 0x8a, 0x88, 0x30, 0x0c, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d,
	0x2e, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c,
	0x02, 0xb3, 0x21, 0x2a, 0x8c, 0xf0, 0xa9, 0x50, 0xe4, 0xe2, 0x06, 0x9b, 0x51, 0x5c, 0x90, 0x9f,
	0x57, 0x9c, 0x8a, 0x5b, 0x89, 0x11, 0x5e, 0x25, 0x39, 0x5c, 0xbc, 0xbe, 0x10, 0x47, 0x7a, 0xa4,
	0x26, 0xa6, 0xa4, 0x16, 0x09, 0x99, 0x70, 0xf1, 0x40, 0x5d, 0x1d, 0x5f, 0x52, 0x59, 0x00, 0x51,
	0xcc, 0x67, 0x24, 0xa8, 0x07, 0x73, 0xbb, 0x1e, 0x54, 0x79, 0x10, 0x37, 0x54, 0x59, 0x48, 0x65,
	0x41, 0xaa, 0x90, 0x2a, 0x17, 0x1f, 0x4c, 0x57, 0x4e, 0x6a, 0x5e, 0x7a, 0x49, 0x86, 0x04, 0x93,
	0x02, 0xa3, 0x06, 0x6b, 0x10, 0x2c, 0x04, 0x7c, 0xc0, 0x82, 0x5a, 0xd5, 0x5c, 0xec, 0x50, 0xed,
	0x42, 0x5c, 0x5c, 0x6c, 0xa1, 0x79, 0xd9, 0x79, 0xf9, 0xe5, 0x02, 0x0c, 0x42, 0x62, 0x5c, 0x42,
	0x50, 0xe1, 0x78, 0x44, 0xb0, 0x08, 0x30, 0xa2, 0x8a, 0xc3, 0x02, 0x43, 0x80, 0x49, 0x48, 0x92,
	0x4b, 0x18, 0x45, 0x3d, 0xc4, 0x7f, 0x02, 0x8d, 0x0d, 0x0e, 0xa8, 0x52, 0x70, 0xaf, 0x0b, 0x34,
	0x35, 0x38, 0x24, 0xb1, 0x81, 0x63, 0xc1, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x7c, 0x87,
	0x95, 0x96, 0x01, 0x00, 0x00,
}
