// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package tutorial

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type XX1Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XX1Request) Reset()         { *m = XX1Request{} }
func (m *XX1Request) String() string { return proto.CompactTextString(m) }
func (*XX1Request) ProtoMessage()    {}
func (*XX1Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *XX1Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XX1Request.Unmarshal(m, b)
}
func (m *XX1Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XX1Request.Marshal(b, m, deterministic)
}
func (m *XX1Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XX1Request.Merge(m, src)
}
func (m *XX1Request) XXX_Size() int {
	return xxx_messageInfo_XX1Request.Size(m)
}
func (m *XX1Request) XXX_DiscardUnknown() {
	xxx_messageInfo_XX1Request.DiscardUnknown(m)
}

var xxx_messageInfo_XX1Request proto.InternalMessageInfo

func (m *XX1Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type XX2Request struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XX2Request) Reset()         { *m = XX2Request{} }
func (m *XX2Request) String() string { return proto.CompactTextString(m) }
func (*XX2Request) ProtoMessage()    {}
func (*XX2Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *XX2Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XX2Request.Unmarshal(m, b)
}
func (m *XX2Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XX2Request.Marshal(b, m, deterministic)
}
func (m *XX2Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XX2Request.Merge(m, src)
}
func (m *XX2Request) XXX_Size() int {
	return xxx_messageInfo_XX2Request.Size(m)
}
func (m *XX2Request) XXX_DiscardUnknown() {
	xxx_messageInfo_XX2Request.DiscardUnknown(m)
}

var xxx_messageInfo_XX2Request proto.InternalMessageInfo

func (m *XX2Request) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Request struct {
	Request1             *XX1Request `protobuf:"bytes,1,opt,name=request1,proto3" json:"request1,omitempty"`
	Request2             *XX2Request `protobuf:"bytes,2,opt,name=request2,proto3" json:"request2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetRequest1() *XX1Request {
	if m != nil {
		return m.Request1
	}
	return nil
}

func (m *Request) GetRequest2() *XX2Request {
	if m != nil {
		return m.Request2
	}
	return nil
}

type XX1Response struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XX1Response) Reset()         { *m = XX1Response{} }
func (m *XX1Response) String() string { return proto.CompactTextString(m) }
func (*XX1Response) ProtoMessage()    {}
func (*XX1Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *XX1Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XX1Response.Unmarshal(m, b)
}
func (m *XX1Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XX1Response.Marshal(b, m, deterministic)
}
func (m *XX1Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XX1Response.Merge(m, src)
}
func (m *XX1Response) XXX_Size() int {
	return xxx_messageInfo_XX1Response.Size(m)
}
func (m *XX1Response) XXX_DiscardUnknown() {
	xxx_messageInfo_XX1Response.DiscardUnknown(m)
}

var xxx_messageInfo_XX1Response proto.InternalMessageInfo

func (m *XX1Response) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type XX2Response struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XX2Response) Reset()         { *m = XX2Response{} }
func (m *XX2Response) String() string { return proto.CompactTextString(m) }
func (*XX2Response) ProtoMessage()    {}
func (*XX2Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *XX2Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XX2Response.Unmarshal(m, b)
}
func (m *XX2Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XX2Response.Marshal(b, m, deterministic)
}
func (m *XX2Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XX2Response.Merge(m, src)
}
func (m *XX2Response) XXX_Size() int {
	return xxx_messageInfo_XX2Response.Size(m)
}
func (m *XX2Response) XXX_DiscardUnknown() {
	xxx_messageInfo_XX2Response.DiscardUnknown(m)
}

var xxx_messageInfo_XX2Response proto.InternalMessageInfo

func (m *XX2Response) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Response struct {
	Response1            *XX1Response `protobuf:"bytes,1,opt,name=response1,proto3" json:"response1,omitempty"`
	Response2            *XX2Response `protobuf:"bytes,2,opt,name=response2,proto3" json:"response2,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetResponse1() *XX1Response {
	if m != nil {
		return m.Response1
	}
	return nil
}

func (m *Response) GetResponse2() *XX2Response {
	if m != nil {
		return m.Response2
	}
	return nil
}

type Message struct {
	Request              *Request  `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Response             *Response `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetRequest() *Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Message) GetResponse() *Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*XX1Request)(nil), "tutorial.XX1Request")
	proto.RegisterType((*XX2Request)(nil), "tutorial.XX2Request")
	proto.RegisterType((*Request)(nil), "tutorial.Request")
	proto.RegisterType((*XX1Response)(nil), "tutorial.XX1Response")
	proto.RegisterType((*XX2Response)(nil), "tutorial.XX2Response")
	proto.RegisterType((*Response)(nil), "tutorial.Response")
	proto.RegisterType((*Message)(nil), "tutorial.Message")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4f, 0x8b, 0x83, 0x30,
	0x10, 0xc5, 0x71, 0x59, 0x56, 0x1d, 0xd9, 0xc3, 0x86, 0x15, 0x3c, 0x5a, 0x4f, 0x85, 0x42, 0xa8,
	0xe3, 0xe7, 0xe8, 0x25, 0x27, 0xaf, 0x16, 0xd2, 0x52, 0xa8, 0xc6, 0x26, 0xf1, 0xfb, 0x97, 0xe6,
	0x8f, 0x4a, 0x5a, 0xbc, 0x0d, 0xbc, 0xdf, 0xcb, 0x7b, 0x93, 0x81, 0xdf, 0x9e, 0x2b, 0xd5, 0x5d,
	0x39, 0x1d, 0xa5, 0xd0, 0x82, 0x24, 0x7a, 0xd2, 0x42, 0xde, 0xba, 0x7b, 0x55, 0x02, 0xb4, 0x6d,
	0xcd, 0xf8, 0x63, 0xe2, 0x4a, 0x13, 0x02, 0xdf, 0x43, 0xd7, 0xf3, 0x22, 0x2a, 0xa3, 0x7d, 0xca,
	0xcc, 0x6c, 0x09, 0xdc, 0x22, 0x7a, 0x88, 0xbd, 0x7c, 0x84, 0x44, 0xda, 0xb1, 0x36, 0x48, 0x86,
	0xff, 0xd4, 0x67, 0xd1, 0x25, 0x88, 0xcd, 0xd4, 0xca, 0x81, 0xc5, 0xd7, 0xbb, 0x03, 0x43, 0x07,
	0x56, 0x3b, 0xc8, 0xcc, 0x4b, 0x6a, 0x14, 0x83, 0xe2, 0x1f, 0x1b, 0x19, 0x04, 0x37, 0x11, 0x0d,
	0xc9, 0xac, 0x37, 0x90, 0x4a, 0x37, 0xfb, 0xda, 0x79, 0x50, 0xdb, 0xaa, 0x6c, 0xe1, 0xd6, 0x26,
	0xdf, 0x3c, 0x0f, 0x9a, 0x87, 0x26, 0xac, 0x2e, 0x10, 0x9f, 0xec, 0x25, 0xc8, 0x01, 0x62, 0xb7,
	0x92, 0x8b, 0xfc, 0x5b, 0xdc, 0x7e, 0x69, 0x4f, 0x10, 0xfa, 0xfa, 0x25, 0xfb, 0x88, 0xcb, 0x22,
	0x6b, 0xda, 0x05, 0xcd, 0xcc, 0xf9, 0xc7, 0xdc, 0xb9, 0x79, 0x06, 0x00, 0x00, 0xff, 0xff, 0x26,
	0xe5, 0x82, 0x01, 0xf8, 0x01, 0x00, 0x00,
}
