// Code generated by protoc-gen-thrift.
// source: echo.proto
// DO NOT EDIT!

/*
This thrift interface description was generated from from one more protobuf descriptors.

It is generated from these files:
	echo.proto

It has these top-level structs:
	Data
*/
package echo

import thrift_pkg "./echo"
import context "context"

// Reference imports to suppress errors if they are not otherwise used.
var _ = context.Background

func conv_Data_to_thrift(msg *Data) *thrift_pkg.Data {
	if msg == nil {
		return nil
	}
	thriftMsg := &thrift_pkg.Data{}

	{
		val := msg.Text
		thriftMsg.Text = &val
	}

	return thriftMsg
}

func conv_Data_to_pb(msg *thrift_pkg.Data) *Data {
	if msg == nil {
		return nil
	}
	pbMsg := &Data{}

	if msg.Text != nil {
		pbMsg.Text = *msg.Text
	}

	return pbMsg
}
