// Code generated by protoc-gen-thrift.
// source: echo.proto
// DO NOT EDIT!

/*
This thrift interface description was generated from from one more protobuf descriptors.

It is generated from these files:
	echo.proto

It has these top-level structs:
	Data
*/
namespace go echo

struct Data {
	1:	optional string	text,
}

service FormatData {
	// Sends a greeting
	Data DoFormat(1: Data in),
}

